# Keep a changelog
- name: Add
  description: Add new features
  color: B60205

- name: Change
  description: Change existing functionality
  color: d73a4a

- name: Deprecate
  description: Mark as soon-to-be removed features
  color: 0075ca

- name: Fix
  description: Fix bug
  color: 0E8A16

- name: Remove
  description: Remove features
  color: cfd3d7

- name: Security
  description: In case of vulnerabilities.
  color: D93F0B

- name: Other
  description: Change development environment or CI service fix..
  color: C2E0C6

- name: Onboarding
  description: onboarding
  color: D4C5F9