name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'Add'
      - 'Change'
  - title: '🧰 Maintenance'
    labels:
      - 'Deprecate'
      - 'Remove'
  - title: '🐛 Bug Security Fixes'
    label:
      - 'Fix'
      - 'Security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'Other'
  - 'Onboarding'

version-resolver:
  major:
    labels:
      - 'Add'
  minor:
    labels:
      - 'Change'
  patch:
    labels:
      - 'Deprecate'
      - 'Remove'
      - 'Fix'
      - 'Security'
  # default: patch
template: |
  ## Changes

  $CHANGES

# autolabeler:
#   - label: Add
#     branch:
#       - '/^feat(ure)?[/-].+/'
#   - label: Change
#     branch:
#       - '/^fix[/-].+/'
#   - label: Deprecate
#     branch:
#       - '/^chore[/-].+/'
#   - label: Remove
#     branch:
#       - '/(refactor|refactoring)[/-].+/'
#   - label: Fix
#     branch:
#       - '/doc(umentation)[/-].+/'
#     files:
#       - '*.md'
#   - label: Security
#     branch:
#       - '/(enhancement|improve)[/-].+/'
#   - label: Other
#     branch:
#       - '/(enhancement|improve)[/-].+/'
#   - label: Onboarding
#     branch:
#       - '/(enhancement|improve)[/-].+/'

autolabeler:
  - label: Add
    branch:
      - '/^feat(ure)?[/-].+/'
  - label: Change
    branch:
      - '/^fix[/-].+/'
  - label: Deprecate
    branch:
      - '/^chore[/-].+/'
  - label: Remove
    branch:
      - '/(refactor|refactoring)[/-].+/'
  - label: Fix
    branch:
      - '/doc(umentation)[/-].+/'
    files:
      - '*.md'
  - label: Security
    branch:
      - '/(enhancement|improve)[/-].+/'
  - label: Other
    branch:
      - '/(enhancement|improve)[/-].+/'
  - label: Onboarding
    branch:
      - '/(enhancement|improve)[/-].+/'