name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'Add'
      - 'Change'
  - title: '🧰 Maintenance'
    labels:
      - 'Deprecate'
      - 'Remove'
  - title: '🐛 Bug Security Fixes'
    label:
      - 'Fix'
      - 'Security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'Other'
  - 'Onboarding'

version-resolver:
  major:
    labels:
      - 'Add'
  minor:
    labels:
      - 'Change'
  patch:
    labels:
      - 'Deprecate'
      - 'Remove'
      - 'Fix'
      - 'Security'
  # default: patch
template: |
  ## Changes

  $CHANGES