name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Types Changes
      labels:
        - types
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - '*'

template: |
   ## Changes

   $CHANGES