name: CI

on: pull_request

# 構文チェック
# config : phpcs.xml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      # PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2 
        with:
          php-version: '8.0'
          tools: composer:v2

      # composer install
      - name: Resolve dependencies
        run: composer require --dev squizlabs/php_codesniffer

      # 構文チェック
      - name: lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./
        run: ./vendor/bin/phpcs --report=emacs --standard=phpcs.xml ./ | reviewdog -reporter=github-check -efm='%f:%l:%c:%m' -level=warning
        # run: ./vendor/bin/phpcbf --report=emacs --standard=phpcs.xml ./ | reviewdog -reporter=github-pr-review -efm='%f:%l:%c:%m'

      # - name: Exit code
      #   run: exit 0


  # 静的解析用
  # config : Rule Levels -l 0
  analyse:
    runs-on: ubuntu-latest
    steps:
      # リポジトリからチェックアウト
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      # PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2 
        with:
          php-version: '8.0'
          tools: composer:v2
      # composer
      - name: Resolve dependencies
        run: composer require --dev phpstan/phpstan
      # PHPStanを実行
      - name: Run PHPstan
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./
        run: ./vendor/bin/phpstan analyse -l 0 --error-format=raw --no-progress --memory-limit=1G | reviewdog -reporter=github-check -f=phpstan -level=warning