name: CI

on: pull_request

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

# 構文チェック
# config : phpcs.xml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      # PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2 
        with:
          php-version: '8.0'
          tools: composer:v2

      # composer install
      - name: Resolve dependencies
        run: composer require --dev squizlabs/php_codesniffer

      # 構文チェック
      - name: lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./
        # プルリクさせない
        run: ./vendor/bin/phpcs --report=emacs --standard=phpcs.xml ./ | reviewdog -reporter=github-pr-check  -efm='%f:%l:%c:%m' -level=error
        # プルリク可
        # run: ./vendor/bin/phpcs --report=emacs --standard=phpcs.xml ./ | reviewdog -reporter=github-pr-review -efm='%f:%l:%c:%m' -level=error
        # 自動整形
        # run: ./vendor/bin/phpcbf --report=emacs --standard=phpcs.xml ./ | reviewdog -reporter=github-pr-review -efm='%f:%l:%c:%m'

      # - name: Exit code
      #   run: exit 0


  # 静的解析用
  # config : Level analyse -l 0
  analyse:
    runs-on: ubuntu-latest
    steps:
      # リポジトリからチェックアウト
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      # PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2 
        with:
          php-version: '8.0'
          tools: composer:v2
      # composer
      - name: Resolve dependencies
        run: composer require --dev phpstan/phpstan
      # PHPStanを実行
      - name: Run PHPstan
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./
        run: ./vendor/bin/phpstan analyse -l 0 --error-format=raw --no-progress --memory-limit=1G | reviewdog -reporter=github-pr-review -f=phpstan -level=error
       
      - name: Success
        uses: rtCamp/action-slack-notify@v2.0.2
        if: success()
        env:
          SLACK_TITLE: Deploy flow / Success
          SLACK_COLOR: good
          SLACK_MESSAGE: Message for success

      - name: Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_TITLE: Deploy flow / Failure
          SLACK_COLOR: danger
          SLACK_MESSAGE: Message for failure

      - name: Cancel
        uses: rtCamp/action-slack-notify@v2.0.2
        if: cancelled()
        env:
          SLACK_TITLE: Deploy flow / cancel
          SLACK_COLOR: danger
          SLACK_MESSAGE: Message for Cancel