name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: shivammathur/setup-php@v1
      - uses: chekalsky/phpcs-action@v1
        with:
          php-version: 7.4
          extensions: intl
          coverage: none

      # - run: mysql -u root -proot -e 'CREATE DATABASE test;'
      # - uses: actions/setup-node@v1
      # - run: npm install -g bats
      # - run: bats -v


      # - run: ls -la

      # - id: changed-files
      #   use: tj-actions/changed-files@v18.5
      #   run: echo steps.changed-files.outputs.all_changed_files